name: IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: IaC Security Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          skip_path: tests
          framework: terraform
          output_format: cli
          soft_fail: false
